### ISSUE TITLE
Upload MLH Badge

### ISSUE THREAD

**Issue by jacobmiller22** [vthacks-org/Live-Site#20]
Upload MLH Badge somewhere on the website.

**Comment by jmc529** [comment]
Although they don't care, they [recommend](https://mlh.io/brand-guidelines) top right

**Comment by jacobmiller22** [comment]
It's uploaded, though I'm not sure how good it looks atm.

**Comment by jmc529** [comment]
You could try using another color to distinguish it or maybe add some margin to the schedule to avoid overlap.

Doesn't look bad though.
